restoring python2 for tests

diff --git a/.github/workflows/build_XSTools.yml b/.github/workflows/build_XSTools.yml
--- a/.github/workflows/build_XSTools.yml
+++ b/.github/workflows/build_XSTools.yml
@@ -18,7 +18,12 @@ on:
   pull_request:
 
 jobs:
-  build_XSTools:
+
+#####################
+## Windows Actions ##
+#####################
+
+  build_XSTools_Windows:
 
     name: XSTools ${{ matrix.os }} (python ${{ matrix.python }}, perl ${{ matrix.perl }}) ${{ matrix.architecture }}
     runs-on: ${{ matrix.os }}
@@ -27,8 +32,9 @@ jobs:
       matrix:
         include:
         - os: windows-2019
-          python: 2.7
+          python: 2.7.18
           architecture: x86
+          python_distr: 'https://www.python.org/ftp/python/2.7.18/python-2.7.18.msi'
           perl: 5.12
           strawberry_distr: 'https://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0-portable.zip'
 
@@ -38,6 +44,249 @@ jobs:
           perl: 5.32
           strawberry_distr: 'https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit-portable.zip'
 
+    steps:
+    - name: GIT checkout
+      uses: actions/checkout@v3
+
+    # setup matrix:
+    # - windows-2019 + python 2.7.18 x86 + strawberry perl 5.12 x86 + strawberry g++ x86
+    # - windows-2022 + python 3      x86 + strawberry perl 5.32 x86 + strawberry g++ x86
+
+    ########################
+    # preparing Windows OS #
+    ########################
+
+    - name: (Windows 2022) Setup python ${{ matrix.python }} ${{ matrix.architecture }}
+      if: matrix.os == 'windows-2022'
+      uses: actions/setup-python@v4
+      with:
+        python-version: ${{ matrix.python }}
+        architecture: ${{ matrix.architecture }}
+
+    - name: (Windows 2019) Check the Python2 cache
+      if: matrix.os == 'windows-2019'
+      id: cache-python2
+      uses: actions/cache@v3
+      with:
+        path: c:\python27
+        key: ${{ runner.os }}-python-${{ matrix.python }}
+
+    - name: (Windows 2019) Replace python to ${{ matrix.python }} ${{ matrix.architecture }}
+      if: matrix.os == 'windows-2019' && steps.cache-python2.outputs.cache-hit != 'true'
+      run: |
+        echo "== python version check:"
+        python -V
+        if ( Test-Path "C:/hostedtoolcache/windows/Python/" ) {
+          echo '== Remove default Python 3:'
+          echo 'rm -r "C:/hostedtoolcache/windows/Python/*"'
+          rm -r "C:/hostedtoolcache/windows/Python/*"
+        }
+        echo "== new python version check:"
+        python -V
+        echo 'rm C:\ProgramData\Chocolatey\bin\python.exe'
+        rm C:\ProgramData\Chocolatey\bin\python.exe
+        echo "=================================="
+        echo "== download python ${{ matrix.python }} (${{ matrix.architecture }})"
+        Invoke-WebRequest ${{ matrix.python_distr }} -OutFile python-2.7.18.msi
+        echo "== install python-2.7.18.msi"
+        cmd /c start /wait msiexec.exe /passive /i python-2.7.18.msi /norestart /L*V "python_install.log" ADDLOCAL=ALL ALLUSERS=1 TARGETDIR=c:\python27
+        echo "== add the path to python27 to the PATH variable"
+        echo "c:\python27" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+
+    - name: Remove default Strawberry perl and g++
+      run: |
+        if ( "${{ matrix.os }}" -eq "windows-2022" ) {
+          echo "== add the path to strawberry to the PATH variable"
+          echo "C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
+        }
+        if ( Test-Path "c:/Strawberry/" ) {
+          echo "== remove c:/Strawberry/*"
+          echo 'rm -r "c:/Strawberry/*"'
+          rm -r "c:/Strawberry/*"
+        }
+        echo "== remove g++ x64"
+        echo 'rm c:/ProgramData/Chocolatey/bin/g++.exe'
+        rm c:/ProgramData/Chocolatey/bin/g++.exe
+
+    - name: Check the Strawberry cache
+      id: cache-strawberry
+      uses: actions/cache@v3
+      with:
+        path: c:\Strawberry
+        key: ${{ runner.os }}-strawberry-${{ matrix.perl }}
+
+    - name: (Windows) Replace perl to Strawberry ${{ matrix.perl }} ${{ matrix.architecture }}
+      if: steps.cache-strawberry.outputs.cache-hit != 'true'
+      run: |
+        echo "::warning ::cache '${{ runner.os }}-strawberry-${{ matrix.perl }}' was NOT found, download the Strawberry perl"
+        echo "===================================="
+        echo "== previous version of Perl:"
+        perl --version
+        echo "===================================="
+        echo "== download Strawberry perl ${{ matrix.perl }} ${{ matrix.architecture }}"
+        Invoke-WebRequest ${{ matrix.strawberry_distr }} -OutFile strawberry.zip
+        echo "===================================="
+        echo "== unpack strawberry-perl ${{ matrix.perl }}"
+        7z.exe x strawberry.zip -o"C:/Strawberry"
+        rm strawberry.zip
+        echo "============================================"
+        echo "== a new version of Perl (should be '${{ matrix.perl }}'):"
+        perl --version
+
+    ###############################
+    # final check of all versions #
+    ###############################
+
+    - name: Environment check
+      run: |
+        echo "== python version check:"
+        python -V
+        echo "======================"
+        echo "== perl version check:"
+        perl --version
+        echo "======================"
+        echo "== Time::HiRes module:"
+        perl -e "use Time::HiRes;"
+        echo "========================="
+        echo "== Compress::Zlib module:"
+        perl -e "use Compress::Zlib;"
+        echo "====================="
+        echo "== g++ version check:"
+        g++ --version
+
+    ####################
+    # building XSTools #
+    ####################
+
+    - name: make XSTools.dll and NetRedirect.dll
+      env:
+          OS: ${{ matrix.os }}
+          PYTHON: ${{ matrix.python }}
+          PERL: ${{ matrix.perl }}
+          ARCHITECTURE: ${{ matrix.architecture }}
+      run: |
+        gmake all
+        echo "================================================================="
+        echo "DONE:"
+        dir src\auto\XSTools\ | findstr "dll"
+        echo "These XSTools.dll and NetRedirect.dll are built using: $env:OS + python $env:PYTHON $env:ARCHITECTURE + strawberry perl $env:PERL $env:ARCHITECTURE + strawberry g++ x86" > src\auto\XSTools\XSTools_notes.txt
+
+    ####################
+    # making artifacts #
+    ####################
+
+    - name: Making artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: ${{ matrix.os }}_perl-${{ matrix.perl }}${{ matrix.architecture }}
+        path: |
+          src\auto\XSTools\XSTools_notes.txt
+          src\auto\XSTools\XSTools.dll
+          src\auto\XSTools\NetRedirect.dll
+
+
+  ########################
+  # start the second job #
+  ########################
+
+  make_Windows_test:
+
+    name: test ${{ matrix.os }} (perl ${{ matrix.perl }}) ${{ matrix.architecture }}
+    needs: build_XSTools_Windows
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+        - os: windows-2019
+          architecture: x86
+          perl: 5.12
+
+        - os: windows-2022
+          architecture: x86
+          perl: 5.32
+
+    steps:
+    - name: GIT checkout
+      uses: actions/checkout@v3
+
+    ########################
+    # preparing Windows OS #
+    ########################
+
+    - name: Remove default Strawberry perl, XSTools.dll
+      if: runner.os == 'Windows'
+      run: |
+        $OS = "${{ matrix.os }}"
+        if ( $OS -eq "windows-2022" ) {
+          echo "Add the path to strawberry to the PATH variable"
+          echo "C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
+          echo "====================="
+        }
+        if ( Test-Path "c:/Strawberry/" ) {
+          echo 'rm -r "c:/Strawberry/*"'
+          rm -r "c:/Strawberry/*"
+          echo "====================="
+        }
+        echo "rm XSTools.dll"
+        rm XSTools.dll
+
+    - name: Check the Strawberry cache
+      id: cache-strawberry
+      if: runner.os == 'Windows'
+      uses: actions/cache@v3
+      with:
+        path: c:\Strawberry
+        key: ${{ runner.os }}-strawberry-${{ matrix.perl }}
+
+    - name: Display an error if the cache is found
+      if: steps.cache-strawberry.outputs.cache-hit != 'true'
+      run: |
+        echo "::error ::cache '${{ runner.os }}-strawberry-${{ matrix.perl }}' was NOT found!!! See the 'Post Check the Strawberry cache' step in the previous job"
+        exit 1
+
+    ###############
+    # final check #
+    ###############
+
+    - name: Environment check
+      run: |
+        echo "== perl version check:"
+        perl --version
+
+    - name: Restoring XTools from artifacts
+      uses: actions/download-artifact@v3
+      with:
+        name: ${{ matrix.os }}_perl-${{ matrix.perl }}${{ matrix.architecture }}
+
+    - name: Checking for XSTools
+      shell: bash
+      run: |
+        echo -e "\e[34m# ls -lh | grep XSTools"
+        ls -lh | grep XSTools
+
+    #############
+    # make test #
+    #############
+
+    - name: Running tests
+      run: |
+        cd src\test
+        perl unittests.pl
+
+
+###################
+## Linux Actions ##
+###################
+
+  build_XSTools_Linux:
+
+    name: XSTools ${{ matrix.os }} (python ${{ matrix.python }}, perl ${{ matrix.perl }}) ${{ matrix.architecture }}
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
         - os: ubuntu-20.04
           python: 2.7
           architecture: x64
@@ -53,69 +302,33 @@ jobs:
       uses: actions/checkout@v3
 
     # setup matrix:
-    # - windows-2019 + python 2.7 x86 + strawberry perl 5.12 x86 + strawberry g++ x86
-    # - windows-2022 + python 3   x86 + strawberry perl 5.32 x86 + strawberry g++ x86
-    # - ubuntu-20.04 + python 2.7 x64 +            perl 5.12 x64
-    # - ubuntu-22.04 + python 3   x64 +            perl last (5.34) x64
-    - name: Setup python ${{ matrix.python }} ${{ matrix.architecture }}
+    # - ubuntu-20.04 + python 2.7.18 x64 + perl 5.12 x64
+    # - ubuntu-22.04 + python 3      x64 + perl last (5.38) x64
+
+    ######################
+    # preparing Linux OS #
+    ######################
+
+    - name: (Ubuntu-22.04) Setup python ${{ matrix.python }} ${{ matrix.architecture }}
+      if: matrix.os == 'ubuntu-22.04'
       uses: actions/setup-python@v4
       with:
         python-version: ${{ matrix.python }}
         architecture: ${{ matrix.architecture }}
 
-    ########################
-    # preparing windows OS #
-    ########################
-
-    - name: (Windows) Remove default Strawberry perl and g++
-      if: runner.os == 'Windows'
+    - name: (Ubuntu-20.04) Setup python ${{ matrix.python }} ${{ matrix.architecture }}
+      if: matrix.os == 'ubuntu-20.04'
       run: |
-        if ( "${{ matrix.os }}" -eq "windows-2022" ) {
-          echo "Add the path to strawberry to the PATH variable"
-          echo "C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
-          echo "====================="
-        }
-        if ( Test-Path "c:/Strawberry/" ) {
-          echo 'rm -r "c:/Strawberry/*"'
-          rm -r "c:/Strawberry/*"
-          echo "====================="
-        }
-        echo "== remove g++ x64"
-        echo 'rm c:/ProgramData/Chocolatey/bin/g++.exe"'
-        rm c:/ProgramData/Chocolatey/bin/g++.exe
+        echo "== python version check:"
+        python -V
+        echo "== rename symbolic link"
+        sudo rm -f /usr/bin/python
+        cd /usr/bin/ && sudo ln -rs python2.7 python
+        # ls -l /usr/bin/ |grep python
+        echo "== new python version check:"
+        python -V
 
-    - name: (Windows) Check the Strawberry cache
-      if: runner.os == 'Windows'
-      id: cache-strawberry
-      uses: actions/cache@v3
-      with:
-        path: c:\Strawberry
-        key: ${{ runner.os }}-strawberry-${{ matrix.perl }}
-
-    - name: (Windows) Replace perl to Strawberry ${{ matrix.perl }} ${{ matrix.architecture }}
-      if: runner.os == 'Windows' && steps.cache-strawberry.outputs.cache-hit != 'true'
-      run: |
-        echo "::warning ::cache '${{ runner.os }}-strawberry-${{ matrix.perl }}' was NOT found, download the Strawberry perl"
-        echo "================================================================="
-        echo "== previous version of Perl:"
-        perl --version
-        echo "================================================================="
-        echo "== download Strawberry perl ${{ matrix.perl }} ${{ matrix.architecture }}"
-        Invoke-WebRequest ${{ matrix.strawberry_distr }} -OutFile strawberry.zip
-        echo "================================================================="
-        echo "== unpack strawberry-perl ${{ matrix.perl }}"
-        7z.exe x strawberry.zip -o"C:/Strawberry"
-        rm strawberry.zip
-        echo "================================================================="
-        echo "== a new version of Perl (should be '${{ matrix.perl }}'):"
-        perl --version
-
-    ######################
-    # preparing linux OS #
-    ######################
-
-    - name: (Linux) Setup perl ${{ matrix.perl }} on linux
-      if: runner.os == 'Linux'
+    - name: Setup perl ${{ matrix.perl }} on linux
       uses: shogo82148/actions-setup-perl@v1
       with:
         perl-version: ${{ matrix.perl }}
@@ -145,22 +358,7 @@ jobs:
     # building XSTools #
     ####################
 
-    - name: (Windows) make XSTools.dll and NetRedirect.dll
-      if: runner.os == 'Windows'
-      env:
-          OS: ${{ matrix.os }}
-          PYTHON: ${{ matrix.python }}
-          PERL: ${{ matrix.perl }}
-          ARCHITECTURE: ${{ matrix.architecture }}
-      run: |
-        gmake all
-        echo "================================================================="
-        echo "DONE:"
-        dir src\auto\XSTools\ | findstr "dll"
-        echo "These XSTools.dll and NetRedirect.dll are built using: $env:OS + python $env:PYTHON $env:ARCHITECTURE + strawberry perl $env:PERL $env:ARCHITECTURE + strawberry g++ x86" > src\auto\XSTools\XSTools_notes.txt
-
-    - name: (Linux) make XSTools.so
-      if: runner.os == 'Linux'
+    - name: make XSTools.so
       env:
           OS: ${{ matrix.os }}
           PYTHON: ${{ matrix.python }}
@@ -173,24 +371,13 @@ jobs:
         echo "======================================================"
         echo "DONE:"
         ls -lh src/auto/XSTools/ | grep so
-        echo "These XSTools.dll and NetRedirect.dll are built using: $OS + python $PYTHON $ARCHITECTURE + strawberry perl $PERL $ARCHITECTURE + strawberry g++ x86" > src/auto/XSTools/XSTools_notes.txt
+        echo "These XSTools.so and NetRedirect.so are built using: $OS + python $PYTHON $ARCHITECTURE + strawberry perl $PERL $ARCHITECTURE + strawberry g++ x86" > src/auto/XSTools/XSTools_notes.txt
 
     ####################
     # making artifacts #
     ####################
 
-    - name: (Windows) Making artifacts on Windows
-      if: runner.os == 'Windows'
-      uses: actions/upload-artifact@v3
-      with:
-        name: ${{ matrix.os }}_perl-${{ matrix.perl }}${{ matrix.architecture }}
-        path: |
-          src\auto\XSTools\XSTools_notes.txt
-          src\auto\XSTools\XSTools.dll
-          src\auto\XSTools\NetRedirect.dll
-
-    - name: (Linux) Making artifacts on Linux
-      if: runner.os == 'Linux'
+    - name: Making artifacts
       uses: actions/upload-artifact@v3
       with:
         name: ${{ matrix.os }}_perl-${{ matrix.perl }}${{ matrix.architecture }}
@@ -203,23 +390,15 @@ jobs:
   # start the second job #
   ########################
 
-  make_test:
+  make_Linux_test:
 
     name: test ${{ matrix.os }} (perl ${{ matrix.perl }}) ${{ matrix.architecture }}
-    needs: build_XSTools
+    needs: build_XSTools_Linux
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
         include:
-        - os: windows-2019
-          architecture: x86
-          perl: 5.12
-
-        - os: windows-2022
-          architecture: x86
-          perl: 5.32
-
         - os: ubuntu-20.04
           architecture: x64
           perl: 5.12
@@ -232,47 +411,11 @@ jobs:
     - name: GIT checkout
       uses: actions/checkout@v3
 
-    ########################
-    # preparing windows OS #
-    ########################
-
-    - name: (Windows) Remove default Strawberry perl, XSTools.dll
-      if: runner.os == 'Windows'
-      run: |
-        $OS = "${{ matrix.os }}"
-        if ( $OS -eq "windows-2022" ) {
-          echo "Add the path to strawberry to the PATH variable"
-          echo "C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
-          echo "====================="
-        }
-        if ( Test-Path "c:/Strawberry/" ) {
-          echo 'rm -r "c:/Strawberry/*"'
-          rm -r "c:/Strawberry/*"
-          echo "====================="
-        }
-        echo "rm XSTools.dll"
-        rm XSTools.dll
-
-    - name: (Windows) Check the Strawberry cache
-      id: cache-strawberry
-      if: runner.os == 'Windows'
-      uses: actions/cache@v3
-      with:
-        path: c:\Strawberry
-        key: ${{ runner.os }}-strawberry-${{ matrix.perl }}
-
-    - name: (Windows) Display an error if the cache is found
-      if: runner.os == 'Windows' && steps.cache-strawberry.outputs.cache-hit != 'true'
-      run: |
-        echo "::error ::cache '${{ runner.os }}-strawberry-${{ matrix.perl }}' was NOT found!!! See the 'Post Check the Strawberry cache' step in the previous job"
-        exit 1
-
     ######################
-    # preparing linux OS #
+    # preparing Linux OS #
     ######################
 
-    - name: (Linux) Setup perl ${{ matrix.perl }}
-      if: runner.os == 'Linux'
+    - name: Setup perl ${{ matrix.perl }}
       uses: shogo82148/actions-setup-perl@v1
       with:
         perl-version: ${{ matrix.perl }}
@@ -301,14 +444,7 @@ jobs:
     # make test #
     #############
 
-    - name: (Windows) running tests on Windows
-      if: runner.os == 'Windows'
-      run: |
-        cd src\test
-        perl unittests.pl
-
-    - name: (Linux) running tests on Linux
-      if: runner.os == 'Linux'
+    - name: Running tests
       run: |
         make test
 
@@ -319,7 +455,7 @@ jobs:
   make_distrib:
 
     name: checking makedist.sh
-    needs: build_XSTools
+    needs: build_XSTools_Linux
     runs-on: ubuntu-latest
 
     steps:
