added automatic testing
Now after a successful build of XSTools, automatic testing starts using XSTools.dll from the first job

diff --git a/.github/workflows/build_XSTools_win.yml b/.github/workflows/build_XSTools_win.yml
--- a/.github/workflows/build_XSTools_win.yml
+++ b/.github/workflows/build_XSTools_win.yml
@@ -1,9 +1,12 @@
-# runs-on:                  https://github.com/actions/virtual-environments
-# setup-python:             https://github.com/actions/setup-python
-# actions-setup-perl:       https://github.com/marketplace/actions/setup-perl-environment
-# Strawberry Perl 5.12.3.0: https://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0-portable.zip
-# Strawberry Perl 5.32.1.1: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit-portable.zip
-# actions-upload-artifact:  https://github.com/actions/upload-artifact
+# workflow syntax           https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
+# runs-on                   https://github.com/actions/virtual-environments
+# setup-python              https://github.com/actions/setup-python
+# actions-setup-perl        https://github.com/marketplace/actions/setup-perl-environment
+# strawberry Perl 5.12.3.0  https://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0-portable.zip
+# strawberry Perl 5.32.1.1  https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit-portable.zip
+# actions-upload-artifact   https://github.com/actions/upload-artifact
+# actions-download-artifact https://github.com/actions/download-artifact
+# actions-cache             https://github.com/actions/cache
 
 name: Build Win
 on:
@@ -17,7 +20,7 @@ on:
 jobs:
   build_XSTools:
 
-    name: XSTools ${{ matrix.os }} (python ${{ matrix.python }}) (perl ${{ matrix.perl }}) ${{ matrix.architecture }}
+    name: XSTools ${{ matrix.os }} (python ${{ matrix.python }}, perl ${{ matrix.perl }}) ${{ matrix.architecture }}
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -32,45 +35,59 @@ jobs:
         - os: windows-latest
           python: 3
           architecture: x86
-          perl: '5.32'
+          perl: 5.32
           strawberry_distr: 'https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit-portable.zip'
 
     steps:
-    - name: Checkout
+    - name: GIT checkout
       uses: actions/checkout@v2
 
-    # setup Windows matrix: python 2.7_x86 + strawberry perl 5.12_x86 and python 3_x86 and strawberry perl 5.32_x86
-    - name: setup-python ${{ matrix.python }} ${{ matrix.architecture }}
+    # setup matrix:
+    # - windows-2016 + python 2.7 x86 + strawberry perl 5.12 x86 + strawberry g++ x86
+    # - windows-2019 + python 3   x86 + strawberry perl 5.32 x86 + strawberry g++ x86
+    - name: Setup python ${{ matrix.python }} ${{ matrix.architecture }}
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python }}
         architecture: ${{ matrix.architecture }}
 
-    - name: Replace perl to ${{ matrix.perl }} ${{ matrix.architecture }}
+    - name: Remove default Strawberry perl and g++
+      shell: bash
       run: |
+        echo -e "\e[34m# mv /c/Strawberry/* /c/Temp/"
+        mv /c/Strawberry/* /c/Temp/
+        echo -e "\e[34m== remove g++ x64"
+        echo -e "\e[34m# rm -f /c/ProgramData/Chocolatey/bin/g++.exe"
+        rm -f /c/ProgramData/Chocolatey/bin/g++.exe
+
+    - name: Check the Strawberry cache
+      id: cache-strawberry
+      uses: actions/cache@v2
+      with:
+        path: c:\Strawberry
+        key: ${{ runner.os }}-strawberry-${{ matrix.perl }}
+
+    - name: Replace perl to Strawberry ${{ matrix.perl }} ${{ matrix.architecture }}
+      if: steps.cache-strawberry.outputs.cache-hit != 'true'
+      run: |
+        echo "Cache NOT found, download the Strawberry pearl"
         echo "================================================================="
         echo "== previous version of Perl:"
-        echo "================================================================="
         perl --version
         echo "================================================================="
         echo "== remove the default perl"
-        echo "================================================================="
         rm -r C:/Strawberry/*
         echo "================================================================="
         echo "== download strawberry perl ${{ matrix.perl }} ${{ matrix.architecture }}"
-        echo "================================================================="
         Invoke-WebRequest ${{ matrix.strawberry_distr }} -OutFile strawberry.zip
+        echo "================================================================="
+        echo "== unpack strawberry-perl"
         7z.exe x strawberry.zip -o"C:/Strawberry"
+        rm strawberry.zip
         echo "================================================================="
         echo "== a new version of Perl:"
-        echo "================================================================="
         perl --version
-        echo "================================================================="
-        echo "== remove g++ x64"
-        echo "================================================================="
-        # package removal takes too long (4 minutes). Instead, we can delete 1 file
-        # choco uninstall mingw
-        rm C:\ProgramData\Chocolatey\bin\g++.exe
+
 
     - name: Environment check
       run: |
@@ -96,17 +113,13 @@ jobs:
         echo "== check g++ version:"
         echo "================================================================="
         g++ --version
-        echo "================================================================="
-        echo "== check gmake version:"
-        echo "================================================================="
-        gmake --version
 
     - name: Run make XSTools.dll
       run: |
         gmake all
         echo "================================================================="
-        ls src\auto\XSTools\XSTools.dll
-        ls src\auto\XSTools\NetRedirect.dll
+        echo "DONE:"
+        dir src\auto\XSTools\ | findstr "dll"
 
     - name: Making artifacts
       uses: actions/upload-artifact@v2
@@ -115,3 +128,66 @@ jobs:
         path: |
           src\auto\XSTools\XSTools.dll
           src\auto\XSTools\NetRedirect.dll
+  make_test:
+
+    name: test ${{ matrix.os }} (perl ${{ matrix.perl }})
+    needs: build_XSTools
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+        - os: windows-2016
+          architecture: x86
+          perl: 5.12
+
+        - os: windows-latest
+          architecture: x86
+          perl: 5.32
+
+    steps:
+    - name: GIT checkout
+      uses: actions/checkout@v2
+
+    - name:  Remove default Strawberry perl, XSTools.dll
+      shell: bash
+      run: |
+        echo -e "\e[34m# mv /c/Strawberry/* /c/Temp/"
+        mv /c/Strawberry/* /c/Temp/
+        echo -e "\e[34m# rm -f XSTools.dll"
+        rm -f XSTools.dll
+
+    - name: Check the Strawberry cache
+      id: cache-strawberry
+      uses: actions/cache@v2
+      with:
+        path: c:\Strawberry
+        key: ${{ runner.os }}-strawberry-${{ matrix.perl }}
+
+    - name: Display an error if the cache is found
+      if: runner.os == 'Windows' && steps.cache-strawberry.outputs.cache-hit != 'true'
+      shell: bash
+      run: |
+        echo -e "\e[30;41m'cache-strawberry' NOT found!!! See the 'Post Check the Strawberry cache' step in the previous job"
+        exit 1
+
+    - name: Environment check
+      run: |
+        echo "== perl version check:"
+        perl --version
+
+    - name: Restoring XTools from artifacts
+      uses: actions/download-artifact@v2
+      with:
+        name: ${{ matrix.os }}_perl${{ matrix.perl }}${{ matrix.architecture }}
+
+    - name: Checking for XSTools
+      shell: bash
+      run: |
+        echo -e "\e[34m# ls -lh | grep XSTools"
+        ls -lh | grep XSTools
+
+    - name: running tests
+      run: |
+        cd src\test
+        perl unittests.pl
