update GitHub Actions (#3537)
* update GitHub Actions

- replaced windows 2016 with windows 2022
- updated task names
- added a new job for checking the makedist.sh script

We are using:
1 VM:
- Windows Server 2019
- python 2.7 x86
- perl 5.12 x86 (Strawberry)
- g++ x86 (Strawberry)
- gmake x86 (Strawberry)

2 VM:
- Windows Server 2022
- python latest (3 x86)
- perl 5.32 x86 (Strawberry)
- g++ x86 (Strawberry)
- gmake x86 (Strawberry)

3 VM:
- Ubuntu 18.04
- python 2.7 x64
- perl 5.12 x64
- g++ x64
- make x64

4 VM:
- Ubuntu latest (20.04)
- python 3 x64
- perl latest x64 (5.34)
- g++ x64
- make x64

diff --git a/.github/workflows/build_XSTools.yml b/.github/workflows/build_XSTools.yml
--- a/.github/workflows/build_XSTools.yml
+++ b/.github/workflows/build_XSTools.yml
@@ -25,13 +25,13 @@ jobs:
       fail-fast: false
       matrix:
         include:
-        - os: windows-2016
+        - os: windows-2019
           python: 2.7
           architecture: x86
           perl: 5.12
           strawberry_distr: 'https://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0-portable.zip'
 
-        - os: windows-latest
+        - os: windows-2022
           python: 3
           architecture: x86
           perl: 5.32
@@ -52,10 +52,10 @@ jobs:
       uses: actions/checkout@v2
 
     # setup matrix:
-    # - windows-2016 + python 2.7 x86 + strawberry perl 5.12 x86 + strawberry g++ x86
-    # - windows-2019 + python 3   x86 + strawberry perl 5.32 x86 + strawberry g++ x86
+    # - windows-2019 + python 2.7 x86 + strawberry perl 5.12 x86 + strawberry g++ x86
+    # - windows-2022 + python 3   x86 + strawberry perl 5.32 x86 + strawberry g++ x86
     # - ubuntu-18.04 + python 2.7 x64 +            perl 5.12 x64
-    # - ubuntu-20.04 + python 3   x64 +            perl 5.32 x64
+    # - ubuntu-20.04 + python 3   x64 +            perl last (5.34) x64
     - name: Setup python ${{ matrix.python }} ${{ matrix.architecture }}
       uses: actions/setup-python@v2
       with:
@@ -66,17 +66,24 @@ jobs:
     # preparing windows OS #
     ########################
 
-    - name: Remove default Strawberry perl and g++
+    - name: (Windows) Remove default Strawberry perl and g++
       if: runner.os == 'Windows'
-      shell: bash
       run: |
-        echo -e "\e[34m# mv /c/Strawberry/* /c/Temp/"
-        mv /c/Strawberry/* /c/Temp/
-        echo -e "\e[34m== remove g++ x64"
-        echo -e "\e[34m# rm -f /c/ProgramData/Chocolatey/bin/g++.exe"
-        rm -f /c/ProgramData/Chocolatey/bin/g++.exe
+        if ( "${{ matrix.os }}" -eq "windows-2022" ) {
+          echo "Add the path to strawberry to the PATH variable"
+          echo "C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
+          echo "====================="
+        }
+        if ( Test-Path "c:/Strawberry/" ) {
+          echo 'rm -r "c:/Strawberry/*"'
+          rm -r "c:/Strawberry/*"
+          echo "====================="
+        }
+        echo "== remove g++ x64"
+        echo 'rm c:/ProgramData/Chocolatey/bin/g++.exe"'
+        rm c:/ProgramData/Chocolatey/bin/g++.exe
 
-    - name: Check the Strawberry cache
+    - name: (Windows) Check the Strawberry cache
       if: runner.os == 'Windows'
       id: cache-strawberry
       uses: actions/cache@v2
@@ -84,32 +91,29 @@ jobs:
         path: c:\Strawberry
         key: ${{ runner.os }}-strawberry-${{ matrix.perl }}
 
-    - name: Replace perl to Strawberry ${{ matrix.perl }} ${{ matrix.architecture }}
+    - name: (Windows) Replace perl to Strawberry ${{ matrix.perl }} ${{ matrix.architecture }}
       if: runner.os == 'Windows' && steps.cache-strawberry.outputs.cache-hit != 'true'
       run: |
-        echo "Cache NOT found, download the Strawberry pearl"
+        echo "::warning ::cache '${{ runner.os }}-strawberry-${{ matrix.perl }}' was NOT found, download the Strawberry perl"
         echo "================================================================="
         echo "== previous version of Perl:"
         perl --version
         echo "================================================================="
-        echo "== remove the default perl"
-        rm -r C:/Strawberry/*
-        echo "================================================================="
-        echo "== download strawberry perl ${{ matrix.perl }} ${{ matrix.architecture }}"
+        echo "== download Strawberry perl ${{ matrix.perl }} ${{ matrix.architecture }}"
         Invoke-WebRequest ${{ matrix.strawberry_distr }} -OutFile strawberry.zip
         echo "================================================================="
-        echo "== unpack strawberry-perl"
+        echo "== unpack strawberry-perl ${{ matrix.perl }}"
         7z.exe x strawberry.zip -o"C:/Strawberry"
         rm strawberry.zip
         echo "================================================================="
-        echo "== a new version of Perl:"
+        echo "== a new version of Perl (should be '${{ matrix.perl }}'):"
         perl --version
 
     ######################
     # preparing linux OS #
     ######################
 
-    - name: Setup perl ${{ matrix.perl }}
+    - name: (Linux) Setup perl ${{ matrix.perl }} on linux
       if: runner.os == 'Linux'
       uses: shogo82148/actions-setup-perl@v1
       with:
@@ -121,7 +125,7 @@ jobs:
 
     - name: Environment check
       run: |
-        echo "python version check:"
+        echo "== python version check:"
         python -V
         echo "======================"
         echo "== perl version check:"
@@ -140,7 +144,7 @@ jobs:
     # building XSTools #
     ####################
 
-    - name: make XSTools.dll and NetRedirect.dll
+    - name: (Windows) make XSTools.dll and NetRedirect.dll
       if: runner.os == 'Windows'
       env:
           OS: ${{ matrix.os }}
@@ -154,7 +158,7 @@ jobs:
         dir src\auto\XSTools\ | findstr "dll"
         echo "These XSTools.dll and NetRedirect.dll are built using: $env:OS + python $env:PYTHON $env:ARCHITECTURE + strawberry perl $env:PERL $env:ARCHITECTURE + strawberry g++ x86" > src\auto\XSTools\XSTools_notes.txt
 
-    - name: make XSTools.so
+    - name: (Linux) make XSTools.so
       if: runner.os == 'Linux'
       env:
           OS: ${{ matrix.os }}
@@ -174,7 +178,7 @@ jobs:
     # making artifacts #
     ####################
 
-    - name: Making artifacts on Windows
+    - name: (Windows) Making artifacts on Windows
       if: runner.os == 'Windows'
       uses: actions/upload-artifact@v2
       with:
@@ -184,7 +188,7 @@ jobs:
           src\auto\XSTools\XSTools.dll
           src\auto\XSTools\NetRedirect.dll
 
-    - name: Making artifacts on Linux
+    - name: (Linux) Making artifacts on Linux
       if: runner.os == 'Linux'
       uses: actions/upload-artifact@v2
       with:
@@ -207,11 +211,11 @@ jobs:
       fail-fast: false
       matrix:
         include:
-        - os: windows-2016
+        - os: windows-2019
           architecture: x86
           perl: 5.12
 
-        - os: windows-latest
+        - os: windows-2022
           architecture: x86
           perl: 5.32
 
@@ -231,16 +235,24 @@ jobs:
     # preparing windows OS #
     ########################
 
-    - name:  Remove default Strawberry perl, XSTools.dll
+    - name: (Windows) Remove default Strawberry perl, XSTools.dll
       if: runner.os == 'Windows'
-      shell: bash
       run: |
-        echo -e "\e[34m# mv /c/Strawberry/* /c/Temp/"
-        mv /c/Strawberry/* /c/Temp/
-        echo -e "\e[34m# rm -f XSTools.dll"
-        rm -f XSTools.dll
+        $OS = "${{ matrix.os }}"
+        if ( $OS -eq "windows-2022" ) {
+          echo "Add the path to strawberry to the PATH variable"
+          echo "C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
+          echo "====================="
+        }
+        if ( Test-Path "c:/Strawberry/" ) {
+          echo 'rm -r "c:/Strawberry/*"'
+          rm -r "c:/Strawberry/*"
+          echo "====================="
+        }
+        echo "rm XSTools.dll"
+        rm XSTools.dll
 
-    - name: Check the Strawberry cache
+    - name: (Windows) Check the Strawberry cache
       id: cache-strawberry
       if: runner.os == 'Windows'
       uses: actions/cache@v2
@@ -248,18 +260,17 @@ jobs:
         path: c:\Strawberry
         key: ${{ runner.os }}-strawberry-${{ matrix.perl }}
 
-    - name: Display an error if the cache is found
+    - name: (Windows) Display an error if the cache is found
       if: runner.os == 'Windows' && steps.cache-strawberry.outputs.cache-hit != 'true'
-      shell: bash
       run: |
-        echo -e "\e[30;41m'cache-strawberry' NOT found!!! See the 'Post Check the Strawberry cache' step in the previous job"
+        echo "::error ::cache '${{ runner.os }}-strawberry-${{ matrix.perl }}' was NOT found!!! See the 'Post Check the Strawberry cache' step in the previous job"
         exit 1
 
     ######################
     # preparing linux OS #
     ######################
 
-    - name: Setup perl ${{ matrix.perl }}
+    - name: (Linux) Setup perl ${{ matrix.perl }}
       if: runner.os == 'Linux'
       uses: shogo82148/actions-setup-perl@v1
       with:
@@ -289,13 +300,54 @@ jobs:
     # make test #
     #############
 
-    - name: running tests on Windows
+    - name: (Windows) running tests on Windows
       if: runner.os == 'Windows'
       run: |
         cd src\test
         perl unittests.pl
 
-    - name: running tests on Linux
+    - name: (Linux) running tests on Linux
       if: runner.os == 'Linux'
       run: |
         make test
+
+  #######################
+  # start the third job #
+  #######################
+
+  make_distrib:
+
+    name: checking makedist.sh
+    needs: build_XSTools
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: GIT checkout
+      uses: actions/checkout@v2
+
+    - name: run "makedist.sh --help"
+      shell: bash
+      run: ./makedist.sh --help || echo -e "\e[34m# done"
+
+    - name: run "makedist.sh --bin"
+      shell: bash
+      run: |
+        echo "::group::script debug"
+          ./makedist.sh --bin
+        echo "::endgroup::"
+        echo -e "\e[34m# ls -lh | grep zip"
+        ls -lh | grep zip
+
+    - name: run "makedist.sh --semibin test_semibin"
+      shell: bash
+      run: |
+        mkdir test_semibin
+        echo "::group::script debug"
+          ./makedist.sh --semibin test_semibin
+        echo "::endgroup::"
+        echo -e "\e[34m# ls -lh | grep test_semibin"
+        ls -lh | grep test_semibin
+
+    - name: run "makedist.sh --unknown"
+      shell: bash
+      run: ./makedist.sh --unknown || echo -e "\e[34m# done"
